# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f8d08d7c89eaed6ef419f8fb6d23be206eb006cf4664a89d4d84bed9090a3ceedcd3fb396129346b1695981d029ac779369a56d0e7d230963a326da57eee289b

test:
  secret_key_base: 031bb4105eec2a5387b65cc3a11f8af655f7d92d1b2bb7f8b1db244e4e3a737dc9a7747fe198cff9381da33cf6f918d478e78ddae1e25e14e4389aad8e0e57de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
